FROM adoptopenjdk/openjdk11:alpine-jre

VOLUME /tmp
ARG JAR_FILE

COPY JAR_FILE app.jar

RUN java_dir=`readlink -f /opt/java/openjdk/bin/java | sed "s:bin/java::"`
RUN apk update \
    && apk add curl \
    && apk add jq \
    && rm -rf /var/cache/apk/*

HEALTHCHECK --interval=5s --timeout=3s --retries=3 \ 
         CMD curl -f http://localhost:8080/actuator/health | jq -e '.status == "UP"' || exit 1
ENTRYPOINT exec java $JAVA_OPTS -jar app.jar

